Feature/task 5
ozonva/ova-reason-api pull request #5
Opened 2021-08-22 12:48 UTC by lmishl

2021-08-22 13:23 UTC, siriusfreak requested changes
Нет тестов, где будет параллельная запись (именно тестов).

2021-08-22 13:23 UTC, siriusfreak commented on internal/saver/saver.go
> +	s.mu.Unlock()
здесь требуется использовать defer, так как если что-то пойдёт не так, то мьютекс останется захваченным

2021-08-22 13:23 UTC, siriusfreak commented on internal/saver/saver.go
> +	time.Sleep(time.Millisecond * 500)
а это зачем?

2021-08-22 13:35 UTC, lmishl commented on internal/saver/saver.go
> +	time.Sleep(time.Millisecond * 500)
это я искусственно создавал гонку данных, чтобы убдиться что мьютекс работает как надо.
теперь можно удалить

2021-08-24 06:30 UTC, siriusfreak requested changes

2021-08-24 06:30 UTC, siriusfreak commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Добавить в gitignore файл ide

2021-08-24 06:30 UTC, siriusfreak commented on .idea/ova-reason-api.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Добавить в gitignore файл ide

2021-08-24 06:30 UTC, siriusfreak commented on cmd/ova-reason-api/main.go
> +	saverObj.Close()
Выглядит некорректно, так как у тебя основной процесс не будет ожидаться завершения горутин и прервёт их. Используй WaitGroup

2021-08-24 06:30 UTC, siriusfreak commented on internal/saver/saver_test.go
> +				saverObj.Save(reason)
В тестах хочется видеть параллельный запуск сейвера, как в main.

2021-08-24 09:54 UTC, siriusfreak approved these changes

2021-08-24 09:54 UTC, merged